Repository privacyidea/privacyidea, pull requests merged in 2019-09, with the labels that each got.

#1847 Broken link fix
  README.rst
Labels: Topic: Documentation

#1853 Increase the width of the UI.
  privacyidea/static/css/content.css
  privacyidea/static/customize/README.rst
Labels: Layer: UI

#1852 Condense menu on small screens
  privacyidea/static/css/menu.css
Labels: Layer: UI

#1858 Reference `push_wait` in the push token documentation.
  doc/configuration/tokens/push.rst
Labels: Topic: Documentation

#1861 Style checkboxes to match up with their labels.
  privacyidea/static/css/content.css
Labels: Layer: UI

#1860 1261/versioning in js and css
  privacyidea/app.py
  privacyidea/static/templates/footer.html
  privacyidea/static/templates/header.html
  privacyidea/webui/login.py
  requirements.txt
Labels: Layer: UI, Type: Enhancement
